import { useEffect, useState } from 'react'
import { HoneyJarScore } from '../components/HoneyJarScore'
import { getChildSession } from '../lib/child-session'
import { supabase } from '../lib/supabase'
import type { DashboardState } from '../lib/dashboard-view-model'

type Data = { role: 'parent' | 'child' | 'teen'; hive?: { hive_name: string; sweetness_score: number }; profile?: { name: string; total_nectar: number }; children?: Array<{ name: string; total_nectar: number }>; pairs: Array<{ id: string; sweetness_score: number; total_nectar: number }>; activities: Array<{ id: string; title: string; scheduled_for?: string }>; promptResponses: Array<{ id: string; teen_private?: boolean }>; nectar?: Array<{ amount: number }>; pendingReviews?: number; privateIndicators?: { prompts: number; artifacts: number } }

export const DashboardPage = () => {
  const [state, setState] = useState<DashboardState<Data>>({ kind: 'loading' })
  useEffect(() => { let active = true; const load = async () => { const child = getChildSession(); const { data: { session } } = await supabase.auth.getSession(); const response = await fetch('/api/dashboard', { headers: { authorization: `Bearer ${child?.token ?? session?.access_token ?? ''}` } }); if (!active) return; if (!response.ok) return setState({ kind: 'error', message: 'We could not load your hive.' }); const data = await response.json() as Data; setState({ kind: 'populated', data }) }; void load(); const channel = supabase.channel('dashboard-core-updates').on('postgres_changes', { event: '*', schema: 'public', table: 'activities' }, load).on('postgres_changes', { event: '*', schema: 'public', table: 'prompt_responses' }, load).on('postgres_changes', { event: '*', schema: 'public', table: 'nectar_transactions' }, load).on('postgres_changes', { event: '*', schema: 'public', table: 'hives' }, load).subscribe(); return () => { active = false; void supabase.removeChannel(channel) } }, [])
  if (state.kind === 'loading') return <main className="page-shell">Loading your hive…</main>
  if (state.kind === 'error' || state.kind === 'empty') return <main className="page-shell">{state.message}</main>
  const { data } = state; const score = data.hive?.sweetness_score ?? data.pairs[0]?.sweetness_score ?? 0
  if (data.role === 'parent') return <main className="page-shell dashboard"><p className="eyebrow">Parent dashboard</p><h1>{data.hive?.hive_name ?? 'Your Hive'}</h1><HoneyJarScore score={score} /><p>{data.pendingReviews ?? 0} completions need review.</p><p>Private teen items: {data.privateIndicators?.prompts ?? 0} prompts and {data.privateIndicators?.artifacts ?? 0} artifacts are locked.</p><h2>Pairs</h2><ul>{data.pairs.map((pair) => <li key={pair.id}>Sweetness {pair.sweetness_score} · Nectar {pair.total_nectar}</li>)}</ul><h2>Scheduled activities</h2><ul>{data.activities.map((activity) => <li key={activity.id}>{activity.title}</li>)}</ul></main>
  if (data.role === 'child') return <main className="page-shell dashboard child-dashboard"><p className="eyebrow">🐝 Buz says hi!</p><h1>Welcome, {data.profile?.name}</h1><HoneyJarScore score={score} /><p>🍯 Your Nectar: {data.profile?.total_nectar ?? 0}</p><p>⭐ Today’s activity: {data.activities[0]?.title ?? 'Your next activity is on its way.'}</p><p>💬 Daily prompt: {data.promptResponses.length ? 'Your reflection is saved.' : 'Share today’s thought.'}</p></main>
  return <main className="page-shell dashboard"><p className="eyebrow">Teen dashboard</p><h1>Welcome, {data.profile?.name}</h1><HoneyJarScore score={score} /><p>Your Nectar: {data.profile?.total_nectar ?? 0}</p><h2>Featured activity</h2><p>{data.activities[0]?.title ?? 'No activity scheduled yet.'}</p><h2>Your privacy</h2><p>You control whether each prompt response and artifact is private from your parent.</p><p>{data.promptResponses.filter((response) => response.teen_private).length} private responses</p></main>
}
