import { useState, type FormEvent } from 'react'
import { generateAllSiblingPairs, type OnboardingChild } from '../lib/onboarding'
import { supabase } from '../lib/supabase'

export const OnboardingPage = () => {
  const [hiveName, setHiveName] = useState(''); const [children, setChildren] = useState<OnboardingChild[]>([{ name: '', birthDate: '' }, { name: '', birthDate: '' }]); const [message, setMessage] = useState('')
  const updateChild = (index: number, key: keyof OnboardingChild, value: string) => setChildren((current) => current.map((child, childIndex) => childIndex === index ? { ...child, [key]: value } : child))
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const { data: { session } } = await supabase.auth.getSession(); const response = await fetch('/api/onboarding', { method: 'POST', headers: { authorization: `Bearer ${session?.access_token ?? ''}`, 'content-type': 'application/json' }, body: JSON.stringify({ hiveName, children: children.map((child) => ({ name: child.name, birth_date: child.birthDate })), pairs: generateAllSiblingPairs(children), settings: { privacy: 'family_only', notifications: { daily_prompts: true } }, assessment: { parent_baseline: 5 } }) }); setMessage(response.ok ? 'Your hive is ready. Welcome Nectar and your first activity are waiting on the dashboard.' : 'We could not finish setting up your hive.') }
  return <main className="page-shell"><p className="eyebrow">Set up your hive</p><h1>Start growing together</h1><form className="form-stack" onSubmit={submit}><label>Hive name<input required maxLength={80} value={hiveName} onChange={(event) => setHiveName(event.target.value)} /></label><p>Privacy is family-only. Daily prompt notifications are enabled.</p>{children.map((child, index) => <fieldset key={index}><legend>Child {index + 1}</legend><label>Name<input required value={child.name} onChange={(event) => updateChild(index, 'name', event.target.value)} /></label><label>Birth date<input required type="date" value={child.birthDate} onChange={(event) => updateChild(index, 'birthDate', event.target.value)} /></label></fieldset>)}{children.length < 4 ? <button className="button button-secondary" onClick={() => setChildren((current) => [...current, { name: '', birthDate: '' }])} type="button">Add child</button> : null}<p>{generateAllSiblingPairs(children).length} sibling pairs will be created.</p><button className="button button-primary" type="submit">Finish hive setup</button>{message ? <p aria-live="polite" className="form-message">{message}</p> : null}</form></main>
}
